[tool.poetry]
name = "data-analysis-page-view-time-series-visualizer"
version = "0.1.0"
description = "An FCC Data Analysis Challenge"

[tool.poetry.dependencies]
pandas = "*"
python = "^3.7"
seaborn = "*"
