[tool.poetry]
name = "data-analysis-page-view-time-series-visualizer"
version = "0.1.0"
description = "An FCC Data Analysis Challenge"
authors = ["pbmchc"]

[tool.poetry.dependencies]
python = "<3.13,>=3.9"
pandas = "^2.1.1"
seaborn = "^0.13.0"
